---
api:
  dashboard: false

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: unix://var/run/docker.sock
    exposedByDefault: false
    useBindPortIP: true

certificatesResolvers:
  http:
    acme:
      email: acme@okeanos.dev
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: http
